import { providerTitle } from './provider.js';

const sidebars = {
  mainSidebar: [
    { type: 'link', label: 'All Providers', href: '/providers' },
    {
      type: 'category',
      label: `${providerTitle} Provider`,
      link: { type: 'doc', id: 'provider-intro' },
      items: [{ type: 'autogenerated', dirName: 'services' }],
    },
    { type: 'doc', id: 'google-control-plane', label: 'GCP Control Plane' },
  ],
};

export default sidebars;
