openapi: 3.0.3
info:
  title: files API
  description: gemini files API
  version: v1beta
paths:
  /v1beta/files:
    get:
      operationId: files.list
      description: Lists the metadata for `File`s owned by the requesting project.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListFilesResponse"
      parameters:
        - in: query
          name: pageSize
          schema:
            type: integer
            format: int32
          description: Optional. Maximum number of `File`s to return per page. If unspecified, defaults to 10. Maximum `page_size` is 100.
        - in: query
          name: pageToken
          schema:
            type: string
          description: Optional. A page token from a previous `ListFiles` call.
  /v1beta/files/{filesId}:
    delete:
      operationId: files.delete
      description: Deletes the `File`.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      parameters:
        - in: path
          name: filesId
          required: true
          schema:
            type: string
    get:
      operationId: files.get
      description: Gets the metadata for the given `File`.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
      parameters:
        - in: path
          name: filesId
          required: true
          schema:
            type: string
  /v1beta/files:register:
    post:
      operationId: files.register
      description: Registers a Google Cloud Storage files with FileService. The user is expected to provide Google Cloud Storage URIs and will receive a File resource for each URI in return. Note that the files are not copied, just registered with File API. If one file fails to register, the whole request fails.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterFilesRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterFilesResponse"
components:
  schemas:
    ListFilesResponse:
      type: object
      properties:
        nextPageToken:
          type: string
          description: A token that can be sent as a `page_token` into a subsequent `ListFiles` call.
        files:
          items:
            $ref: "#/components/schemas/File"
          type: array
          description: The list of `File`s.
      id: ListFilesResponse
      description: Response for `ListFiles`.
    Empty:
      id: Empty
      description: "A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); }"
      type: object
      properties: {}
    File:
      type: object
      properties:
        name:
          type: string
          description: 'Immutable. Identifier. The `File` resource name. The ID (name excluding the "files/" prefix) can contain up to 40 characters that are lowercase alphanumeric or dashes (-). The ID cannot start or end with a dash. If the name is empty on create, a unique name will be generated. Example: `files/123-456`'
        expirationTime:
          readOnly: true
          format: google-datetime
          type: string
          description: Output only. The timestamp of when the `File` will be deleted. Only set if the `File` is scheduled to expire.
        state:
          readOnly: true
          type: string
          enum:
            - STATE_UNSPECIFIED
            - PROCESSING
            - ACTIVE
            - FAILED
          description: Output only. Processing state of the File.
          enumDescriptions:
            - The default value. This value is used if the state is omitted.
            - File is being processed and cannot be used for inference yet.
            - File is processed and available for inference.
            - File failed processing.
        downloadUri:
          description: Output only. The download uri of the `File`.
          type: string
          readOnly: true
        sizeBytes:
          type: string
          readOnly: true
          format: int64
          description: Output only. Size of the file in bytes.
        sha256Hash:
          type: string
          readOnly: true
          format: byte
          description: Output only. SHA-256 hash of the uploaded bytes.
        updateTime:
          description: Output only. The timestamp of when the `File` was last updated.
          readOnly: true
          format: google-datetime
          type: string
        videoMetadata:
          readOnly: true
          $ref: "#/components/schemas/VideoFileMetadata"
          description: Output only. Metadata for a video.
        mimeType:
          readOnly: true
          type: string
          description: Output only. MIME type of the file.
        createTime:
          description: Output only. The timestamp of when the `File` was created.
          type: string
          readOnly: true
          format: google-datetime
        source:
          enumDescriptions:
            - Used if source is not specified.
            - Indicates the file is uploaded by the user.
            - Indicates the file is generated by Google.
            - Indicates the file is a registered, i.e. a Google Cloud Storage file.
          type: string
          enum:
            - SOURCE_UNSPECIFIED
            - UPLOADED
            - GENERATED
            - REGISTERED
          description: Source of the File.
        error:
          description: Output only. Error status if File processing failed.
          readOnly: true
          $ref: "#/components/schemas/Status"
        uri:
          type: string
          readOnly: true
          description: Output only. The uri of the `File`.
        displayName:
          type: string
          description: 'Optional. The human-readable display name for the `File`. The display name must be no more than 512 characters in length, including spaces. Example: "Welcome Image"'
      id: File
      description: "A file uploaded to the API. Next ID: 15"
    RegisterFilesRequest:
      type: object
      properties:
        uris:
          type: array
          items:
            type: string
          description: "Required. The Google Cloud Storage URIs to register. Example: `gs://bucket/object`."
      id: RegisterFilesRequest
      description: Request for `RegisterFiles`.
    RegisterFilesResponse:
      type: object
      properties:
        files:
          items:
            $ref: "#/components/schemas/File"
          type: array
          description: The registered files to be used when calling GenerateContent.
      id: RegisterFilesResponse
      description: Response for `RegisterFiles`.
    VideoFileMetadata:
      id: VideoFileMetadata
      description: Metadata for a video `File`.
      type: object
      properties:
        videoDuration:
          type: string
          format: google-duration
          description: Duration of the video.
    Status:
      id: Status
      description: "The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors)."
      type: object
      properties:
        message:
          type: string
          description: A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.
        code:
          type: integer
          format: int32
          description: The status code, which should be an enum value of google.rpc.Code.
        details:
          description: A list of messages that carry the error details. There is a common set of message types for APIs to use.
          type: array
          items:
            type: object
  x-stackQL-resources:
    files:
      id: gemini.files.files
      name: files
      title: Files
      methods:
        list:
          operation:
            $ref: "#/paths/~1v1beta~1files/get"
          response:
            mediaType: application/json
            openAPIDocKey: "200"
            objectKey: $.files
          config:
            pagination:
              requestToken:
                key: pageToken
                location: query
              responseToken:
                key: $.nextPageToken
                location: body
            queryParamPushdown:
              top:
                paramName: pageSize
        delete:
          operation:
            $ref: "#/paths/~1v1beta~1files~1{filesId}/delete"
          response:
            mediaType: application/json
            openAPIDocKey: "200"
        get:
          operation:
            $ref: "#/paths/~1v1beta~1files~1{filesId}/get"
          response:
            mediaType: application/json
            openAPIDocKey: "200"
        register:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: "#/paths/~1v1beta~1files:register/post"
          response:
            mediaType: application/json
            openAPIDocKey: "200"
          request:
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/files/methods/get"
          - $ref: "#/components/x-stackQL-resources/files/methods/list"
        insert:
          - $ref: "#/components/x-stackQL-resources/files/methods/register"
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/files/methods/delete"
        replace: []
servers:
  - url: https://generativelanguage.googleapis.com
